mongo:
    url: 'mongodb://biomaj-mongo:27017'
    db: 'biomaj_cron'

cron:
    cli: 'biomaj-cli.py'

consul:
    host: 'biomaj-consul'
    # Unique agent identifier name among biomaj downloaders
    id: null

web:
    debug: true
    port: 5000
    local_endpoint: 'http://biomaj-internal-proxy'

tls:
    key: null
    cert: null

log_config:
    'version': 1
    'formatters':
        'generic':
            'format': '%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s'
    'handlers':
        'console':
            'class': 'logging.StreamHandler'
            'formatter': 'generic'
            'level': 'DEBUG'
    'loggers':
        'root':
            'level': 'INFO'
            'handlers':
                - 'console'
        'biomaj':
            'level': 'DEBUG'
            'handlers':
                - 'console'
    'disable_existing_loggers': False
